# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Develop\Vocabual\layouts\review.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(768, 576)
        Frame.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.wordLabel_2 = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(90)
        font.setBold(True)
        font.setWeight(75)
        self.wordLabel_2.setFont(font)
        self.wordLabel_2.setStyleSheet("")
        self.wordLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel_2.setObjectName("wordLabel_2")
        self.verticalLayout.addWidget(self.wordLabel_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.A = PillPushButton(Frame)
        self.A.setMinimumSize(QtCore.QSize(200, 80))
        self.A.setObjectName("A")
        self.verticalLayout_3.addWidget(self.A)
        self.B = PillPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B.sizePolicy().hasHeightForWidth())
        self.B.setSizePolicy(sizePolicy)
        self.B.setMinimumSize(QtCore.QSize(200, 80))
        self.B.setObjectName("B")
        self.verticalLayout_3.addWidget(self.B)
        self.C = PillPushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.C.sizePolicy().hasHeightForWidth())
        self.C.setSizePolicy(sizePolicy)
        self.C.setMinimumSize(QtCore.QSize(200, 80))
        self.C.setObjectName("C")
        self.verticalLayout_3.addWidget(self.C)
        self.D = PillPushButton(Frame)
        self.D.setMinimumSize(QtCore.QSize(200, 80))
        self.D.setObjectName("D")
        self.verticalLayout_3.addWidget(self.D)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.wordLabel_2.setText(_translate("Frame", "abandon"))
        self.A.setText(_translate("Frame", "不认识"))
        self.B.setText(_translate("Frame", "认识"))
        self.C.setText(_translate("Frame", "认识"))
        self.D.setText(_translate("Frame", "不认识"))
from qfluentwidgets import PillPushButton
