# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\VSwork\helloworld\Vocabual\layouts\review.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(768, 534)
        Frame.setStyleSheet("ainWindow {\n"
"    background-image: url(file:///E:/VSwork/helloworld/Vocabual/layouts/648965794_cover.png);  /* 使用资源文件路径 */\n"
"    background-repeat: no-repeat;  /* 不重复显示 */\n"
"    background-position: center;  /* 居中显示 */\n"
"    background-attachment: fixed;  /* 固定背景 */\n"
"    background-origin: content;  /* 从内容区开始显示背景 */\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.favouriteButton = TogglePushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favouriteButton.sizePolicy().hasHeightForWidth())
        self.favouriteButton.setSizePolicy(sizePolicy)
        self.favouriteButton.setMinimumSize(QtCore.QSize(24, 24))
        self.favouriteButton.setMaximumSize(QtCore.QSize(40, 40))
        self.favouriteButton.setObjectName("favouriteButton")
        self.horizontalLayout.addWidget(self.favouriteButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.wordLabel = QtWidgets.QLabel(Frame)
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono SemiBold")
        font.setPointSize(90)
        font.setBold(True)
        font.setWeight(75)
        self.wordLabel.setFont(font)
        self.wordLabel.setStyleSheet("")
        self.wordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wordLabel.setObjectName("wordLabel")
        self.verticalLayout.addWidget(self.wordLabel)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.knownButton_3 = PushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knownButton_3.sizePolicy().hasHeightForWidth())
        self.knownButton_3.setSizePolicy(sizePolicy)
        self.knownButton_3.setMinimumSize(QtCore.QSize(200, 80))
        self.knownButton_3.setObjectName("knownButton_3")
        self.horizontalLayout_11.addWidget(self.knownButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.unknownButton_3 = PushButton(Frame)
        self.unknownButton_3.setMinimumSize(QtCore.QSize(200, 80))
        self.unknownButton_3.setObjectName("unknownButton_3")
        self.horizontalLayout_11.addWidget(self.unknownButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.knownButton_2 = PushButton(Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.knownButton_2.sizePolicy().hasHeightForWidth())
        self.knownButton_2.setSizePolicy(sizePolicy)
        self.knownButton_2.setMinimumSize(QtCore.QSize(200, 80))
        self.knownButton_2.setObjectName("knownButton_2")
        self.horizontalLayout_2.addWidget(self.knownButton_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.unknownButton_2 = PushButton(Frame)
        self.unknownButton_2.setMinimumSize(QtCore.QSize(200, 80))
        self.unknownButton_2.setObjectName("unknownButton_2")
        self.horizontalLayout_2.addWidget(self.unknownButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.progressBar = ProgressBar(Frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_6.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.favouriteButton.setText(_translate("Frame", "⭐"))
        self.wordLabel.setText(_translate("Frame", "abandon"))
        self.knownButton_3.setText(_translate("Frame", "认识"))
        self.unknownButton_3.setText(_translate("Frame", "不认识"))
        self.knownButton_2.setText(_translate("Frame", "认识"))
        self.unknownButton_2.setText(_translate("Frame", "不认识"))
        self.label_4.setText(_translate("Frame", "今日剩余"))
from qfluentwidgets import ProgressBar, PushButton, TogglePushButton
